import test from 'node:test';
import assert from 'node:assert/strict';
import {createHash} from 'node:crypto';
import {readFile,stat} from 'node:fs/promises';
const read=path=>readFile(new URL(`../${path}`,import.meta.url),'utf8');
test('legacy layered globe asset remains valid but is no longer the active TOP',async()=>{const svg=await read('site/assets/visual/hero/astera-globe-exact-layered.svg');for(const marker of ['data-astera-layered-svg="true"','id="base-image"','id="effects-behind"','id="effects-orbits"','id="effects-particles"','id="effects-front"'])assert.match(svg,new RegExp(marker));assert.doesNotMatch(svg,/<script\b|<foreignObject\b|<text\b|<style\b/);const home=await read('site/templates/home.html');assert.doesNotMatch(home,/astera-globe-exact-layered|astera-globe-top\.webp|data-astera-hero/);assert.match(home,/astera-original-transparent\.svg/)});
test('legacy restoration patch remains byte exact for routes that still retain the reusable asset set',async()=>{const patch=await readFile(new URL('../site/assets/images/astera-globe-lower-right-restoration.webp',import.meta.url));assert.equal(patch.length,1834);assert.equal(patch.subarray(0,4).toString('ascii'),'RIFF');assert.equal(patch.subarray(8,12).toString('ascii'),'WEBP');assert.equal(createHash('sha256').update(patch).digest('hex'),'6ae36d248ac206ec4e7785991ef9df8c60feab1bd466371aa3500ec92188357a')});
test('build keeps pinned local GSAP without weakening CSP',async()=>{const packageJson=JSON.parse(await read('package.json'));const packageLock=JSON.parse(await read('package-lock.json'));assert.equal(packageJson.dependencies.gsap,'3.12.2');assert.equal(packageLock.packages['node_modules/gsap'].version,'3.12.2');const headers=await read('site/public/_headers');assert.match(headers,/script-src 'self'/);assert.doesNotMatch(headers,/cdnjs|jsdelivr|unsafe-inline/);const runtimeInfo=await stat(new URL('../site/assets/vendor/gsap-3.12.2.min.js',import.meta.url));assert.ok(runtimeInfo.size>50000)});
test('built TOP uses only the exact uploaded SVG in its visual area',async()=>{const html=await read('site/dist/index.html');assert.match(html,/class="top-visual"/);assert.match(html,/assets\/visual\/hero\/astera-original-transparent\.svg/);assert.doesNotMatch(html,/assets\/images\/astera-globe-top\.webp|data-svg-src="\/assets\/visual\/hero\/astera-globe-exact-layered\.svg"|data-astera-hero|<canvas/);const top=await readFile(new URL('../site/dist/assets/visual/hero/astera-original-transparent.svg',import.meta.url));assert.equal(top.length,3097567);assert.equal(createHash('sha256').update(top).digest('hex'),'84a9988a47157a9b6f01602fee08f1b176dbe7d6996a4fd42b07ca644551c5e2')});
