function compile(gl,type,source){
  const shader=gl.createShader(type);gl.shaderSource(shader,source);gl.compileShader(shader);
  if(!gl.getShaderParameter(shader,gl.COMPILE_STATUS)){const msg=gl.getShaderInfoLog(shader)||'shader compile failed';gl.deleteShader(shader);throw new Error(msg)}
  return shader;
}
function program(gl,vs,fs){const p=gl.createProgram();const a=compile(gl,gl.VERTEX_SHADER,vs),b=compile(gl,gl.FRAGMENT_SHADER,fs);gl.attachShader(p,a);gl.attachShader(p,b);gl.linkProgram(p);gl.deleteShader(a);gl.deleteShader(b);if(!gl.getProgramParameter(p,gl.LINK_STATUS)){const msg=gl.getProgramInfoLog(p)||'program link failed';gl.deleteProgram(p);throw new Error(msg)}return p}
const VS=`#version 300 es
in vec2 a_position;void main(){gl_Position=vec4(a_position,0.,1.);}`;
const FS=`#version 300 es
precision highp float;out vec4 outColor;uniform vec2 u_resolution;uniform float u_time;uniform vec2 u_pointer;
float hash(vec2 p){p=fract(p*vec2(123.34,456.21));p+=dot(p,p+45.32);return fract(p.x*p.y);} 
float noise(vec2 p){vec2 i=floor(p),f=fract(p);f=f*f*(3.-2.*f);return mix(mix(hash(i),hash(i+vec2(1,0)),f.x),mix(hash(i+vec2(0,1)),hash(i+vec2(1,1)),f.x),f.y);} 
float fbm(vec2 p){float v=0.,a=.5;for(int i=0;i<4;i++){v+=a*noise(p);p=p*2.03+vec2(9.2,5.7);a*=.5;}return v;} 
void main(){vec2 uv=(gl_FragCoord.xy-.5*u_resolution.xy)/min(u_resolution.x,u_resolution.y);vec2 p=uv;float t=u_time*.025;float n=fbm(p*1.55+vec2(t,-t*.7));float n2=fbm(p*2.4+vec2(-t*.8,t*.45));float cloud=smoothstep(.44,.82,n*.72+n2*.36);float vign=smoothstep(1.18,.18,length(uv*vec2(.78,1.0)));vec3 c=vec3(0.);c+=vec3(.035,.18,.46)*cloud*vign*.22;c+=vec3(.19,.07,.48)*smoothstep(.55,.9,n2)*vign*.10;vec2 guv=gl_FragCoord.xy/44.;vec2 id=floor(guv),f=fract(guv)-.5;float h=hash(id);float star=step(.988,h)*smoothstep(.11,0.,length(f))*mix(.18,.9,hash(id+7.));star*=.68+.32*sin(u_time*(.4+hash(id)*1.5)+h*25.);c+=star*vec3(.58,.82,1.);vec2 mp=(u_pointer-.5)*vec2(u_resolution.x/u_resolution.y,1.);float halo=exp(-5.8*length(uv-mp));c+=halo*vec3(.025,.09,.2);outColor=vec4(c,1.);}`;
function init2D(canvas,root,reduced){const ctx=canvas.getContext('2d');if(!ctx)return()=>{};let raf=0,active=true;const stars=Array.from({length:90},(_,i)=>({x:(i*97%997)/997,y:(i*151%991)/991,r:.4+((i*71)%100)/120,a:.12+((i*43)%100)/230}));function resize(){const d=Math.min(devicePixelRatio||1,1.5),r=root.getBoundingClientRect();canvas.width=Math.max(1,Math.round(r.width*d));canvas.height=Math.max(1,Math.round(r.height*d));canvas.style.width=`${r.width}px`;canvas.style.height=`${r.height}px`;ctx.setTransform(d,0,0,d,0,0)}function draw(){const r=root.getBoundingClientRect();ctx.clearRect(0,0,r.width,r.height);for(const s of stars){ctx.globalAlpha=s.a;ctx.fillStyle='#bfe8ff';ctx.beginPath();ctx.arc(s.x*r.width,s.y*r.height,s.r,0,Math.PI*2);ctx.fill()}ctx.globalAlpha=1;if(!reduced&&active)raf=requestAnimationFrame(draw)}resize();draw();const ro=new ResizeObserver(resize);ro.observe(root);const io=new IntersectionObserver(([e])=>{active=e.isIntersecting;if(active&&!reduced&&!raf)raf=requestAnimationFrame(draw);if(!active&&raf){cancelAnimationFrame(raf);raf=0}},{rootMargin:'160px'});io.observe(root);return()=>{ro.disconnect();io.disconnect();if(raf)cancelAnimationFrame(raf)}}
export function initCosmicSpace(root){const canvas=root?.querySelector('[data-cosmic-space]');if(!canvas)return()=>{};const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;const gl=canvas.getContext('webgl2',{alpha:false,antialias:false,powerPreference:'low-power'});if(!gl)return init2D(canvas,root,reduced);let p;try{p=program(gl,VS,FS)}catch(err){console.warn('Cosmic interface WebGL fallback:',err);const replacement=canvas.cloneNode(false);canvas.replaceWith(replacement);return init2D(replacement,root,reduced)}const locPos=gl.getAttribLocation(p,'a_position'),locRes=gl.getUniformLocation(p,'u_resolution'),locTime=gl.getUniformLocation(p,'u_time'),locPointer=gl.getUniformLocation(p,'u_pointer');const buffer=gl.createBuffer();gl.bindBuffer(gl.ARRAY_BUFFER,buffer);gl.bufferData(gl.ARRAY_BUFFER,new Float32Array([-1,-1,3,-1,-1,3]),gl.STATIC_DRAW);gl.useProgram(p);gl.enableVertexAttribArray(locPos);gl.vertexAttribPointer(locPos,2,gl.FLOAT,false,0,0);let pointer=[.5,.5],raf=0,active=true,last=0;function resize(){const d=Math.min(devicePixelRatio||1,1.5),r=root.getBoundingClientRect(),w=Math.max(1,Math.round(r.width*d)),h=Math.max(1,Math.round(r.height*d));if(canvas.width!==w||canvas.height!==h){canvas.width=w;canvas.height=h;canvas.style.width=`${r.width}px`;canvas.style.height=`${r.height}px`;gl.viewport(0,0,w,h)}}function draw(ts){resize();gl.uniform2f(locRes,canvas.width,canvas.height);gl.uniform1f(locTime,reduced?0:ts*.001);gl.uniform2f(locPointer,pointer[0],pointer[1]);gl.drawArrays(gl.TRIANGLES,0,3);raf=0;if(active&&!reduced)raf=requestAnimationFrame(draw)}function move(e){const r=root.getBoundingClientRect();pointer=[Math.min(1,Math.max(0,(e.clientX-r.left)/r.width)),Math.min(1,Math.max(0,1-(e.clientY-r.top)/r.height))];if(reduced&&!raf)raf=requestAnimationFrame(draw)}root.addEventListener('pointermove',move,{passive:true});const ro=new ResizeObserver(()=>{resize();if(reduced&&!raf)raf=requestAnimationFrame(draw)});ro.observe(root);const io=new IntersectionObserver(([e])=>{active=e.isIntersecting;if(active&&!raf)raf=requestAnimationFrame(draw);if(!active&&raf){cancelAnimationFrame(raf);raf=0}},{rootMargin:'180px'});io.observe(root);const vis=()=>{active=!document.hidden&&root.getBoundingClientRect().bottom>-180&&root.getBoundingClientRect().top<innerHeight+180;if(active&&!raf)raf=requestAnimationFrame(draw)};document.addEventListener('visibilitychange',vis);resize();raf=requestAnimationFrame(draw);return()=>{root.removeEventListener('pointermove',move);document.removeEventListener('visibilitychange',vis);ro.disconnect();io.disconnect();if(raf)cancelAnimationFrame(raf);gl.deleteBuffer(buffer);gl.deleteProgram(p)}}
